language: python
sudo: false
python:
- '2.7'
install: 
- pip install -e .
- pip install pytest
script:
- py.test tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: fAAojHwIc4gLZmZPA2WWaLWl6ioc1zolIA6paxRkFjIR5oCXcvhFVh5a2HlKM8HaoCgnJol3zglGObkltm38769+MmYLxuLta4AUT375fcxC7/Y4v04zFMv8havg66M+wBImwrOe1mfwYZTnLkUdhJIN6IeevwJD4bDjPzqzj4o=
  on:
    tags: true
    repo: vmalloc/pyrefactor
